import type { Item } from "@/types";

export const ITEMS = {
	wild_horseradish: {
		name: "Wild Horseradish",
		seasons: ["spring"],
		skills: ["foraging"],
		source: "Spring Foraging",
	},
	daffodil: {
		name: "Daffodil",
		seasons: ["spring"],
		skills: ["foraging"],
		source: "Spring Foraging; Pierre's Shop at the Flower Dance",
	},
	leek: {
		name: "Leek",
		seasons: ["spring"],
		skills: ["foraging"],
		source: "Spring Foraging",
	},
	dandelion: {
		name: "Dandelion",
		seasons: ["spring"],
		skills: ["foraging"],
		source: "Spring Foraging; Pierre's Shop at the Flower Dance",
	},
	spring_onion: {
		name: "Spring Onion",
		seasons: ["spring"],
		skills: ["foraging"],
		source: "Spring Foraging",
	},
	grape: {
		name: "Grape",
		seasons: ["summer", "fall"],
		skills: ["foraging", "farming"],
		source: "Summer Foraging",
	},
	spice_berry: {
		name: "Spice Berry",
		seasons: ["summer"],
		skills: ["foraging"],
		source: "Summer Foraging",
	},
	sweet_pea: {
		name: "Sweet Pea",
		seasons: ["summer"],
		skills: ["foraging"],
		source: "Summer Foraging",
	},
	common_mushroom: {
		name: "Common Mushroom",
		seasons: ["fall"],
		skills: ["foraging"],
		source: "Fall Foraging; Farm Cave (mushroom option)",
	},
	wild_plum: {
		name: "Wild Plum",
		seasons: ["fall"],
		skills: ["foraging"],
		source: "Fall Foraging",
	},
	hazelnut: {
		name: "Hazelnut",
		seasons: ["fall"],
		skills: ["foraging"],
		source: "Fall Foraging",
	},
	blackberry: {
		name: "Blackberry",
		seasons: ["fall"],
		skills: ["foraging"],
		source: "Fall Foraging",
	},
	winter_root: {
		name: "Winter Root",
		seasons: ["winter"],
		skills: ["foraging", "combat"],
		source: "Winter Foraging; Drop from Slimes (floors 41-79)",
	},
	crystal_fruit: {
		name: "Crystal Fruit",
		seasons: ["winter"],
		skills: ["foraging", "combat"],
		source: "Winter Foraging; Drop from Coal Sprites (floors 41-79)",
	},
	snow_yam: {
		name: "Snow Yam",
		seasons: ["winter"],
		skills: ["foraging"],
		source: "Tilling soil or Artifact Spots during Winter",
	},
	crocus: {
		name: "Crocus",
		seasons: ["winter"],
		skills: ["foraging"],
		source: "Winter Foraging",
	},
	holly: {
		name: "Holly",
		seasons: ["winter"],
		skills: ["foraging"],
		source: "Winter Foraging",
	},
	wood: {
		name: "Wood",
		seasons: [],
		skills: ["foraging"],
		source: "Chopping Trees",
	},
	stone: {
		name: "Stone",
		seasons: [],
		skills: ["mining"],
		source: "Mining",
	},
	hardwood: {
		name: "Hardwood",
		seasons: [],
		skills: ["foraging", "mining"],
		source: "Chopping large stumps with an upgraded axe; Crates in The Mines",
	},
	sap: {
		name: "Sap",
		seasons: [],
		skills: ["foraging"],
		source: "Chopping Trees; Drop from Slimes (floors 41-79)",
	},
	coconut: {
		name: "Coconut",
		seasons: [],
		skills: ["foraging"],
		source: "Foraging in The Desert",
	},
	cactus_fruit: {
		name: "Cactus Fruit",
		seasons: [],
		skills: ["foraging"],
		source: "Foraging in The Desert",
	},
	cave_carrot: {
		name: "Cave Carrot",
		seasons: [],
		skills: ["mining"],
		source: "Crates in The Mines; Tilling soil in The Mines",
	},
	red_mushroom: {
		name: "Red Mushroom",
		seasons: [],
		skills: ["foraging", "mining"],
		source: "Foraging in The Mines; Farm Cave (mushroom option)",
	},
	purple_mushroom: {
		name: "Purple Mushroom",
		seasons: [],
		skills: ["foraging", "mining"],
		source: "Foraging in The Mines; Farm Cave (mushroom option)",
	},
	white_algae: {
		name: "White Algae",
		seasons: [],
		skills: ["fishing", "combat"],
		source:
			"Drop from monsters and crates in The Mines; Farm Cave (mushroom option)",
	},
	maple_syrup: {
		name: "Maple Syrup",
		seasons: [],
		skills: ["foraging"],
		source: "Harvested from maple trees using a Tapper",
	},
	oak_resin: {
		name: "Oak Resin",
		seasons: [],
		skills: ["foraging"],
		source: "Harvested from oak trees using a Tapper",
	},
	pine_tar: {
		name: "Pine Tar",
		seasons: [],
		skills: ["foraging"],
		source: "Harvested from pine trees using a Tapper",
	},
	morel: {
		name: "Morel",
		seasons: [],
		skills: ["foraging"],
		source: "Farm Cave (mushroom option)",
	},
	parsnip: {
		name: "Parsnip",
		seasons: ["spring"],
		skills: ["farming"],
		source: "Spring Crops",
	},
	green_bean: {
		name: "Green Bean",
		seasons: ["spring"],
		skills: ["farming"],
		source: "Spring Crops",
	},
	cauliflower: {
		name: "Cauliflower",
		seasons: ["spring"],
		skills: ["farming"],
		source: "Spring Crops",
	},
	potato: {
		name: "Potato",
		seasons: ["spring"],
		skills: ["farming"],
		source: "Spring Crops",
	},
	hops: {
		name: "Hops",
		seasons: ["summer"],
		skills: ["farming"],
		source: "Summer crops",
	},
	tomato: {
		name: "Tomato",
		seasons: ["summer"],
		skills: ["farming"],
		source: "Summer Crops",
	},
	hot_pepper: {
		name: "Hot Pepper",
		seasons: ["summer"],
		skills: ["farming"],
		source: "Summer Crops",
	},
	blueberry: {
		name: "Blueberry",
		seasons: ["summer"],
		skills: ["farming"],
		source: "Summer Crops",
	},
	melon: {
		name: "Melon",
		seasons: ["summer"],
		skills: ["farming"],
		source: "Summer Crops",
	},
	corn: {
		name: "Corn",
		seasons: ["summer", "fall"],
		skills: ["farming"],
		source: "Summer / Fall Crops",
	},
	eggplant: {
		name: "Eggplant",
		seasons: ["fall"],
		skills: ["farming"],
		source: "Fall Crops",
	},
	pumpkin: {
		name: "Pumpkin",
		seasons: ["fall"],
		skills: ["farming"],
		source: "Fall Crops",
	},
	yam: {
		name: "Yam",
		seasons: ["fall"],
		skills: ["farming"],
		source: "Fall Crops",
	},
	ancient_fruit: {
		name: "Ancient Fruit",
		seasons: ["spring", "summer", "fall"],
		skills: ["farming"],
		source:
			"Spring / Summer / Fall Crops; Seed obtained from Ancient Seed artifact",
	},
	sweet_gem_berry: {
		name: "Sweet Gem Berry",
		seasons: ["fall"],
		skills: ["farming"],
		source: "Fall Crops; Seed (Rare Seed) purchased from the Traveling Cart",
	},
	milk: {
		name: "Milk (Any)",
		seasons: [],
		skills: ["farming"],
		source: "Cows, Goats",
		iconPath: "Milk",
	},
	large_milk: {
		name: "Large Milk",
		seasons: [],
		skills: ["farming"],
		source: "Cows",
	},
	large_goat_milk: {
		name: "Large Goat Milk",
		seasons: [],
		skills: ["farming"],
		source: "Goats",
	},
	egg: {
		name: "Egg (Any)",
		seasons: [],
		skills: ["farming"],
		source: "Drop from Chickens",
		iconPath: "Egg",
	},
	large_egg_brown: {
		name: "Large Brown Egg",
		seasons: [],
		skills: ["farming"],
		source: "Drop from Brown Chickens",
		iconPath: "Large_Brown_Egg",
	},
	large_egg_white: {
		name: "Large White Egg",
		seasons: [],
		skills: ["farming"],
		source: "Drop from White Chickens",
		iconPath: "Large_Egg",
	},
	dinosaur_mayonnaise: {
		name: "Dinosaur Mayonnaise",
		seasons: [],
		skills: ["farming"],
		source: "Dinosaur Egg in Mayonnaise Machine",
	},
	wool: {
		name: "Wool",
		seasons: [],
		skills: ["farming"],
		source: "Sheep, Rabbits",
	},
	duck_egg: {
		name: "Duck Egg",
		seasons: [],
		skills: ["farming"],
		source: "Drop from Ducks",
	},
	duck_feather: {
		name: "Duck Feather",
		seasons: [],
		skills: ["farming"],
		source: "Drop from Ducks",
	},
	roe: {
		name: "Roe",
		seasons: [],
		skills: ["farming"],
		source: "Fish Pond product from most Fish",
	},
	aged_roe: {
		name: "Roe",
		seasons: [],
		skills: ["farming"],
		source: "Preserves Jar product from Roe",
	},
	caviar: {
		name: "Roe",
		seasons: [],
		skills: ["farming"],
		source: "Preserves Jar product from Sturgeon Roe",
	},
	squid_ink: {
		name: "Squid Ink",
		seasons: [],
		skills: ["farming"],
		source:
			"Fish Pond product from Squid and Midnight Squid; Drop from Squid Kid",
	},
	tulip: {
		name: "Tulip",
		seasons: ["spring"],
		skills: ["farming"],
		source: "Spring Crops",
	},
	blue_jazz: {
		name: "Blue Jazz",
		seasons: ["spring"],
		skills: ["farming"],
		source: "Spring Crops",
	},
	summer_spangle: {
		name: "Summer Spangle",
		seasons: ["summer"],
		skills: ["farming"],
		source: "Summer Crops",
	},
	fairy_rose: {
		name: "Fairy Rose",
		seasons: ["fall"],
		skills: ["farming"],
		source: "Fall Crops",
	},
	truffle_oil: {
		name: "Truffle Oil",
		seasons: [],
		skills: ["farming"],
		source: "Truffle in Oil Maker",
	},
	cloth: {
		name: "Cloth",
		seasons: [],
		skills: ["farming", "foraging"],
		source: "Wool in Loom; 10% chance when recycling Soggy Newspaper",
	},
	goat_cheese: {
		name: "Goat Cheese",
		seasons: [],
		skills: ["farming"],
		source: "Goat Milk in Cheese Press",
	},
	cheese: {
		name: "Cheese",
		seasons: [],
		skills: ["farming"],
		source: "Cow Milk in Cheese Press",
	},
	honey: {
		name: "Honey",
		seasons: ["spring", "summer", "fall"],
		skills: ["farming"],
		source: "Product from Beehive",
	},
	jelly: {
		name: "Jelly",
		seasons: [],
		skills: ["farming", "foraging"],
		source: "Fruit in Preserves Jar",
	},
	mead: {
		name: "Mead",
		seasons: [],
		skills: ["farming"],
		source: "Honey in Keg",
	},
	pale_ale: {
		name: "Pale Ale",
		seasons: [],
		skills: ["farming"],
		source: "Hops in Keg",
	},
	juice: {
		name: "Juice",
		seasons: [],
		skills: ["farming"],
		source: "Vegetable in Keg",
	},
	green_tea: {
		name: "Green Tea",
		seasons: [],
		skills: ["farming"],
		source: "Tea Leaves in Keg",
	},
	apple: {
		name: "Apple",
		seasons: ["fall"],
		skills: ["farming"],
		source: "Apple Trees during Fall; Farm Cave (fruit bat option)",
	},
	apricot: {
		name: "Apricot",
		seasons: ["spring"],
		skills: ["farming"],
		source: "Apricot Trees during Spring; Farm Cave (fruit bat option)",
	},
	orange: {
		name: "Orange",
		seasons: ["summer", "spring", "fall", "winter"],
		skills: ["farming", "foraging"],
		source: "Orange Trees during Summer; Farm Cave (fruit bat option)",
	},
	peach: {
		name: "Peach",
		seasons: ["summer"],
		skills: ["farming"],
		source: "Peach Trees during Summer; Farm Cave (fruit bat option)",
	},
	pomegranate: {
		name: "Pomegranate",
		seasons: ["fall"],
		skills: ["farming"],
		source: "Pomegranate Trees during Fall; Farm Cave (fruit bat option)",
	},
	cherry: {
		name: "Cherry",
		seasons: [],
		skills: ["farming", "foraging"],
		source: "Cherry Trees during Spring; Farm Cave (fruit bat option)",
	},
	sunfish: {
		name: "Sunfish",
		seasons: ["spring", "summer"],
		skills: ["fishing"],
		source: "River | Sunny | 6am-7pm | Spring and Summer",
	},
	catfish: {
		name: "Catfish",
		seasons: ["spring", "fall"],
		skills: ["fishing"],
		source:
			"River | Raining | 6am-midnight | Spring and Fall; Secret Woods | Raining | 6am-midnight | Summer",
	},
	shad: {
		name: "Shad",
		seasons: ["spring", "summer", "fall"],
		skills: ["fishing"],
		source: "River | Raining | 9am-2am | Spring, Summer, and Fall",
	},
	tiger_trout: {
		name: "Tiger Trout",
		seasons: ["fall", "winter"],
		skills: ["fishing"],
		source: "River | 6am-7pm | Fall and Winter",
	},
	largemouth_bass: {
		name: "Largemouth Bass",
		seasons: [],
		skills: ["fishing"],
		source: "Lake | 6am-7pm | All Seasons",
	},
	carp: {
		name: "Carp",
		seasons: [],
		skills: ["fishing"],
		source:
			"Lake | 6am-2am | Spring, Summer, Fall; Secret Woods or Sewer | 6am-2am | All Seasons",
	},
	bullhead: {
		name: "Bullhead",
		seasons: [],
		skills: ["fishing"],
		source: "Lake | 6am-2am | All Seasons",
	},
	sturgeon: {
		name: "Sturgeon",
		seasons: ["summer", "winter"],
		skills: ["fishing"],
		source: "Lake | 6am-7pm | Summer and Winter",
	},
	sardine: {
		name: "Sardine",
		seasons: ["spring", "fall", "winter"],
		skills: ["fishing"],
		source: "Ocean | 6am-7pm | Spring, Fall, and Winter",
	},
	tuna: {
		name: "Tuna",
		seasons: ["summer", "winter"],
		skills: ["fishing"],
		source: "Ocean | 6am-7pm | Summer and Winter",
	},
	red_snapper: {
		name: "Red Snapper",
		seasons: ["summer", "fall"],
		skills: ["fishing"],
		source: "Ocean | Raining | 6am-7pm | Summer and Fall",
	},
	tilapia: {
		name: "Tilapia",
		seasons: ["summer", "fall"],
		skills: ["fishing"],
		source: "Ocean | 6am-2pm | Summer and Fall",
	},
	walleye: {
		name: "Walleye",
		seasons: ["fall", "winter"],
		skills: ["fishing"],
		source: "River | Raining | 12pm-2am | Fall and Winter",
	},
	bream: {
		name: "Bream",
		seasons: [],
		skills: ["fishing"],
		source: "River | 6pm-2am | All Seasons",
	},
	eel: {
		name: "Eel",
		seasons: ["spring", "fall"],
		skills: ["fishing"],
		source: "Ocean | Raining | 4pm-2am | Spring or Fall",
	},
	lobster: {
		name: "Lobster",
		seasons: [],
		skills: ["fishing"],
		source: "Caught in Crab Pots (ocean)",
	},
	crayfish: {
		name: "Crayfish",
		seasons: [],
		skills: ["fishing"],
		source: "Caught in Crab Pots (freshwater)",
	},
	crab: {
		name: "Crab",
		seasons: [],
		skills: ["fishing", "combat"],
		source:
			"Caught in Crab Pots (ocean); Drop from Rock Crabs or Lava Crabs in The Mines",
	},
	cockle: {
		name: "Cockle",
		seasons: [],
		skills: ["fishing", "foraging"],
		source: "Caught in Crab Pots (ocean); Beach Foraging",
	},
	mussel: {
		name: "Mussel",
		seasons: [],
		skills: ["fishing", "foraging"],
		source: "Caught in Crab Pots (ocean); Beach Foraging",
	},
	shrimp: {
		name: "Shrimp",
		seasons: [],
		skills: ["fishing"],
		source: "Caught in Crab Pots (ocean)",
	},
	snail: {
		name: "Snail",
		seasons: [],
		skills: ["fishing"],
		source: "Caught in Crab Pots (freshwater)",
	},
	periwinkle: {
		name: "Periwinkle",
		seasons: [],
		skills: ["fishing"],
		source: "Caught in Crab Pots (freshwater)",
	},
	oyster: {
		name: "Oyster",
		seasons: [],
		skills: ["fishing", "foraging"],
		source: "Caught in Crab Pots (ocean); Beach Foraging",
	},
	clam: {
		name: "Clam",
		seasons: [],
		skills: ["fishing", "foraging"],
		source: "Caught in Crab Pots (ocean); Beach Foraging",
	},
	pufferfish: {
		name: "Pufferfish",
		seasons: ["summer"],
		skills: ["fishing"],
		source:
			"Ocean | Sunny | 12pm-4pm | Summer; Purchased from the Traveling Cart",
	},
	ghostfish: {
		name: "Ghostfish",
		seasons: [],
		skills: ["fishing", "combat"],
		source:
			"Floors 20 & 60 in The Mines | Anytime | All Seasons; Drop from Ghosts",
	},
	sandfish: {
		name: "Sandfish",
		seasons: [],
		skills: ["fishing", "combat"],
		source:
			"The Desert | 6am-8pm | All Seasons; Purchased from the Traveling Cart",
	},
	woodskip: {
		name: "Woodskip",
		seasons: [],
		skills: ["fishing"],
		source:
			"Secret Woods | 6am-2am | All Seasons; Purchased from the Traveling Cart",
	},
	lava_eel: {
		name: "Lava Eel",
		seasons: [],
		skills: ["fishing"],
		source: "Floor 100 in The Mines | 6am-2am | All Seasons",
	},
	scorpion_carp: {
		name: "Scorpion Carp",
		seasons: [],
		skills: ["fishing"],
		source: "The Desert | 6am-2am | All Seasons",
	},
	octopus: {
		name: "Octopus",
		seasons: ["summer"],
		skills: ["fishing"],
		source:
			"Ocean | 6am-2am | All Seasons; Rarely in Garbage Cans; Submarine ride at the Night Market",
	},
	blobfish: {
		name: "Blobfish",
		seasons: ["winter"],
		skills: ["fishing"],
		source: "Submarine ride at the Night Market",
	},
	void_salmon: {
		name: "Void Salmon",
		seasons: [],
		skills: ["fishing"],
		source: "Witch's Swamp | 6am-2am | All Seasons",
	},
	copper_bar: {
		name: "Copper Bar",
		seasons: [],
		skills: ["mining"],
		source: "Smelting Copper Ore in the Furnace",
	},
	iron_bar: {
		name: "Iron Bar",
		seasons: [],
		skills: ["mining"],
		source: "Smelting Iron Ore in the Furnace",
	},
	gold_bar: {
		name: "Gold Bar",
		seasons: [],
		skills: ["mining"],
		source: "Smelting Gold Ore in the Furnace",
	},
	quartz: {
		name: "Quartz",
		seasons: [],
		skills: ["mining"],
		source: "Foraging on all floors of The Mines",
	},
	earth_crystal: {
		name: "Earth Crystal",
		seasons: [],
		skills: ["mining"],
		source: "Foraging on floors 1-39 of The Mines; Geodes, Omni Geodes",
	},
	frozen_tear: {
		name: "Frozen Tear",
		seasons: [],
		skills: ["mining"],
		source:
			"Foraging on floors 40-79 of The Mines; Frozen Geodes, Omni Geodes; Drop from Dust Sprites",
	},
	fire_quartz: {
		name: "Fire Quartz",
		seasons: [],
		skills: ["mining"],
		source: "Foraging on floors 80-120 of The Mines; Magma Geodes, Omni Geodes",
	},
	slime: {
		name: "Slime",
		seasons: [],
		skills: ["combat"],
		source: "Drop from Slimes",
	},
	bat_wing: {
		name: "Bat Wing",
		seasons: [],
		skills: ["combat"],
		source: "Drop from Bats in The Mines and Skull Cavern",
	},
	solar_essence: {
		name: "Solar Essence",
		seasons: [],
		skills: ["combat"],
		source:
			"Drop from Ghosts, Squid Kids in The Mines; Fish Pond product from Sunfish; Sold by Krobus",
	},
	void_essence: {
		name: "Void Essence",
		seasons: [],
		skills: ["combat"],
		source:
			"Drop from Shadow Brutes in The Mines; Fish Pond product from Void Salmon; Sold by Krobus",
	},
	bone_fragment: {
		name: "Bone Fragment",
		seasons: [],
		skills: ["combat"],
		source:
			"Drop from Skeletons in The Mines; Crates and Barrels in Skull Cavern; Artifact Spots",
	},
	amethyst: {
		name: "Amethyst",
		seasons: [],
		skills: ["mining", "fishing"],
		source: "Found in The Mines; Panning; Fishing Treasure Chests",
	},
	diamond: {
		name: "Diamond",
		seasons: [],
		skills: ["mining", "fishing"],
		source: "Found in The Mines; Panning; Fishing Treasure Chests",
	},
	emerald: {
		name: "Emerald",
		seasons: [],
		skills: ["mining", "fishing"],
		source: "Found in The Mines; Panning; Fishing Treasure Chests",
	},
	ruby: {
		name: "Ruby",
		seasons: [],
		skills: ["mining", "fishing"],
		source: "Found in The Mines; Panning; Fishing Treasure Chests",
	},
	topaz: {
		name: "Topaz",
		seasons: [],
		skills: ["mining", "fishing"],
		source: "Found in The Mines; Panning; Fishing Treasure Chests",
	},
	iridium_ore: {
		name: "Iridium Ore",
		seasons: [],
		skills: ["mining"],
		source: "The Mines, Quarry, Skull Cavern, Magma Geode, Omni Geode",
	},
	battery_pack: {
		name: "Battery Pack",
		seasons: [],
		skills: [],
		source: "Lightning Rod; Sold by Traveling Cart",
	},
	refined_quartz: {
		name: "Refined Quartz",
		seasons: [],
		skills: ["mining"],
		source:
			"Smelting Quartz or Fire Quartz in furnace; Broken Glasses or Broken CD in Recyling Machine",
	},
	fiddlehead_fern: {
		name: "Fiddlehead Fern",
		seasons: ["summer"],
		skills: ["foraging"],
		source: "Summer Foraging in Secret Woods",
	},
	truffle: {
		name: "Truffle",
		seasons: ["spring", "summer", "fall"],
		skills: ["farming"],
		source: "Found by happy pigs while outdoors",
	},
	poppy: {
		name: "Poppy",
		seasons: ["summer"],
		skills: ["farming"],
		source: "Summer Crops",
	},
	maki_roll: {
		name: "Maki Roll",
		seasons: [],
		skills: ["fishing"],
		source: "Acquired by Cooking (recipe sources: Queen of Sauce, The Saloon)",
	},
	fried_egg: {
		name: "Fried Egg",
		seasons: [],
		skills: ["farming"],
		source: "Acquired by Cooking",
	},
	sea_urchin: {
		name: "Sea Urchin",
		seasons: [],
		skills: ["foraging"],
		source: "Beach Foraging, after fixing the bridge to the tide pools",
	},
	sunflower: {
		name: "Sunflower",
		seasons: ["summer", "fall"],
		skills: ["farming"],
		source: "Summer / Fall Crops",
	},
	aquamarine: {
		name: "Aquamarine",
		seasons: [],
		skills: ["mining"],
		source: "Aquamarine Nodes and boxes in The Mines; Fishing Treasure Chests",
	},
	red_cabbage: {
		name: "Red Cabbage",
		seasons: ["summer"],
		skills: ["farming"],
		source:
			"Summer Crops (seeds sold by Pierre from year 2 onwards); Sold by Traveling Cart",
	},
	nautilus_shell: {
		name: "Nautilus Shell",
		seasons: ["winter"],
		skills: ["foraging"],
		source: "Winter Beach Foraging",
	},
	chub: {
		name: "Chub",
		seasons: [],
		skills: ["fishing"],
		source: "Lake | 6am-2am | All Seasons",
	},
	frozen_geode: {
		name: "Frozen Geode",
		seasons: [],
		skills: ["mining"],
		source: "The Mines (floors 40-79)",
	},
	wheat: {
		name: "Wheat",
		seasons: ["summer", "fall"],
		skills: ["farming"],
		source: "Summer / Fall Crops",
	},
	hay: {
		name: "Hay",
		seasons: [],
		skills: ["farming"],
		source:
			"Sold by Marnie's Ranch or Desert Trader; Harvest from Grass or Wheat using a scythe",
	},
	wine: {
		name: "Wine",
		seasons: [],
		skills: ["farming", "foraging"],
		source: "Fruit in a keg",
	},
	rabbits_foot: {
		name: "Rabbit's Foot",
		seasons: [],
		skills: ["farming", "combat"],
		source: "Drop from Rabbits; Drop from Serpents in Skull Cavern (0.8%)",
	},
	beet: {
		name: "Beet",
		seasons: ["fall"],
		skills: ["farming"],
		source: "Fall Crops (seeds purchased at Oasis)",
	},
	amaranth: {
		name: "Amaranth",
		seasons: ["fall"],
		skills: ["farming"],
		source: "Fall Crops",
	},
	starfruit: {
		name: "Starfruit",
		seasons: ["summer"],
		skills: ["farming"],
		source: "Summer Crops (seeds purchased at Oasis)",
	},
	iridium_bar: {
		name: "Iridium Bar",
		seasons: [],
		skills: ["mining"],
		source: "Smelting Iridium Ore in a Furnace",
	},
	prismatic_shard: {
		name: "Prismatic Shard",
		seasons: [],
		skills: ["mining"],
		source:
			"Mystic Stones (25%) in The Mines; Iridium Node (4%) in Skull Cavern; Fishing Treasure Chests",
	},
	salmonberry: {
		name: "Salmonberry",
		seasons: ["spring"],
		skills: ["foraging"],
		source: "Spring Foraging (days 15-18 only)",
	},
	cookie: {
		name: "Cookie",
		seasons: [],
		skills: [],
		source: "Cooking product",
	},
	ancient_doll: {
		name: "Ancient Doll",
		seasons: [],
		skills: ["foraging", "combat"],
		source:
			"Artifact dug up from Mountain, Bus Stop, Forest, or Town; Fishing Treasure Chests",
	},
	ice_cream: {
		name: "Ice Cream",
		seasons: ["summer"],
		skills: [],
		source:
			"Cooking product; Sold by Ice Cream Stand during Summer, or from Oasis on Sundays",
	},
	wheat_flour: {
		name: "Wheat Flour",
		seasons: [],
		skills: ["farming"],
		source: "Mill product from Wheat; Sold by Pierre's",
	},
	"2500_gold": {
		name: "2,500 Gold",
		seasons: [],
		skills: ["farming", "mining", "foraging", "fishing", "combat"],
		source: "",
		iconPath: "/bundles/2500.png",
	},
	"5000_gold": {
		name: "5,000 Gold",
		seasons: [],
		skills: ["farming", "mining", "foraging", "fishing", "combat"],
		source: "",
		iconPath: "/bundles/5000.png",
	},
	"10000_gold": {
		name: "10,000 Gold",
		seasons: [],
		skills: ["farming", "mining", "foraging", "fishing", "combat"],
		source: "",
		iconPath: "/bundles/10000.png",
	},
	"25000_gold": {
		name: "25,000 Gold",
		seasons: [],
		skills: ["farming", "mining", "foraging", "fishing", "combat"],
		source: "",
		iconPath: "/bundles/25000.png",
	},
} as const satisfies { [key: string]: Item };
